### ISSUE TITLE
windows packaging

### ISSUE THREAD

**Issue by ghost** [veandco/go-sdl2-example#1]
Windows is prety difficut these days thanks to Windwos Store and the changes going on.

If you happen to know where there is a good example of packiang for Windows ( even if not SDL), i would be most grateful.

**Comment by veeableful** [comment]
I don't have experience on Windows packaging so I can't help you with this, I'm sorry :(

Have you looked at the official documents?
https://msdn.microsoft.com/en-us/library/cc766795.aspx
https://docs.microsoft.com/en-us/windows/uwp/packaging/manual-packaging-root

**Comment by ghost** [comment]
thanks for links.

its easy to make an MSI, its more the issue of winrt and appx. thats not possible becaue of need for a new golang GOOS apparently because of the Windows Store Certification Kit blocking some calls that golang makes. It picks them up once you submit it to the store PAIN i know..

here is the Issue:
https://github.com/golang/go/issues/21805

So no golang SDL apps are possible in the Windows store as it stands. Its huge loss !!

will close...
